// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI5OMPHv51nMYs7n69NuVlMPjMO_MxV-c',
    appId: '1:117374285328:web:a59ac78022550e97d33c95',
    messagingSenderId: '117374285328',
    projectId: 'note-ed4f0',
    authDomain: 'note-ed4f0.firebaseapp.com',
    storageBucket: 'note-ed4f0.appspot.com',
    measurementId: 'G-V529DDNHK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPcPxmSDEiyCk2clBHqa_OOzh3rbyCvJM',
    appId: '1:117374285328:android:a097b6425bb26b58d33c95',
    messagingSenderId: '117374285328',
    projectId: 'note-ed4f0',
    storageBucket: 'note-ed4f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC06-hZlqnTHRzOTGbVckFph8Zu2mXp5nM',
    appId: '1:117374285328:ios:de4c078c6ebe1c61d33c95',
    messagingSenderId: '117374285328',
    projectId: 'note-ed4f0',
    storageBucket: 'note-ed4f0.appspot.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC06-hZlqnTHRzOTGbVckFph8Zu2mXp5nM',
    appId: '1:117374285328:ios:c7877ec7e89917f7d33c95',
    messagingSenderId: '117374285328',
    projectId: 'note-ed4f0',
    storageBucket: 'note-ed4f0.appspot.com',
    iosBundleId: 'com.example.note.RunnerTests',
  );
}
